import { Mountain } from './types';

export const mountains: Mountain[] = [
  {
    id: 0,
    name: "Slieve Donard",
    tagline: "Sliabh Dónairt: Mountain of (St.) Domhangart",
    image: "/images/slieve-donard.jpg",
    height: "850m",
    lat: 54.1789,
    lng: -5.9122,
    terrain: "Mostly rock if following the Glen river but heather if approaching from most other routes. The steepest part of the climb to the summit is mostly grass and rock under foot.",
    additional: "Although Slieve Donard is a tough climb it is the most popular mountain in the mournes for the recreational walker. It provides nice views out over Newcastle, Murlough Bay & into the some of the other peaks of the mournes.",
    photo: "Taken just before sunrise in November 2008. A view of the Carn and style at the peak of Donard. (By Darragh McConville)"
  },
  {
    id: 1,
    name: "Slieve Binnian",
    tagline: "Sliabh Binneáin: Mountain of the small peak",
    image: "/images/binniansouth.jpg",
    height: "747m",
    lat: 54.1411,
    lng: -5.9928,
    terrain: "Mostly rock at the top with South, Summit & North Tors. The side are mostly heather, grass & mud especially in wet weather.",
    additional: "Slieve Binnian is a great mountain to hike. The summit is almost 1 mile long and consists of the South Tor, Summit Tor & the North Tor with each side providing great views over the Mourne Mountain range and the Irish sea.",
    photo: "This photo was taken by Peter Barr"
  },
  {
    id: 2,
    name: "Slieve Bearnagh",
    tagline: "Sliabh Bearnach: Gapped mountain",
    image: "/images/bearnaghcloud.jpg",
    height: "739m",    lat: 54.1522,
    lng: -5.9778,    terrain: "",
    additional: "",
    photo: "This photo was taken by Darragh Mc Conville from the Brandy Pad and gives a beautiful view of the North and Summit Tors of Bearnagh."
  },
  {
    id: 3,
    name: "Slieve Commedagh",
    tagline: "Sliabh Coimhéideach: Watching/Guarding mountain",
    image: "/images/Commedagh-frost.jpg",
    height: "765m",
    lat: 54.1686,
    lng: -5.9464,
    terrain: "",
    additional: "",
    photo: "Slieve Commedagh summit on a frosty December morning. This photo was taken by Darragh Mc Conville."
  },
  {
    id: 4,
    name: "Slieve Lamagan",
    tagline: "Sliabh Lámhagáin: Creeping/crawling mountain",
    image: "/images/lamagan-river.jpg",
    height: "704m",
    lat: 54.1519,
    lng: -5.9594,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from Annalong Valley below the Blue Lough."
  },
  {
    id: 5,
    name: "Slieve Meelmore",
    tagline: "Sliabh Míol Mór: Big mountain of the ants",
    image: "/images/climbing-meelmore.jpg",
    height: "687m",
    lat: 54.1619,
    lng: -5.9681,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Peter Barr in 2008 when walking up the Slieve Bearnagh side of Slieve Meelmore."
  },
  {
    id: 6,
    name: "Doan",
    tagline: "Dún Maol Chobha: Maol Chobhas fort",
    image: "/images/doanview1.jpg",
    height: "594m",
    lat: 54.1628,
    lng: -5.9856,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Darragh Mc Conville. The waterway to the left of Doan is Silent Valley reservoir."
  },
  {
    id: 7,
    name: "Ben Crom",
    tagline: "Binn Crom or Beann Chrom: Curved/stooped peak",
    image: "/images/crom-from-corragh1.jpg",
    height: "526m",
    lat: 54.1375,
    lng: -5.9711,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Darragh Mc Conville from Slieve Corragh."
  },
  {
    id: 8,
    name: "Slieve Muck",
    tagline: "Sliabh Muc: Mountain of the pigs",
    image: "/images/slieve-muck-south1.jpg",
    height: "675m",
    lat: 54.1267,
    lng: -6.0036,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland."
  },
  {
    id: 9,
    name: "Slievenaglogh",
    tagline: "Sliabh na gCloch: Mountain of the stones/rocks",
    image: "/images/slievenaglogh.jpg",
    height: "445m",
    lat: 54.1244,
    lng: -5.9575,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Darragh Mc Conville. To the left/east of Slievenaglogh is Silent Valley reservoir."
  },
  {
    id: 10,
    name: "Slieve Meelbeg",
    tagline: "Sliabh Miol Beag: Little mountain of the ants",
    image: "/images/meelbeg-from-doan1.jpg",
    height: "708m",
    lat: 54.1581,
    lng: -5.9828,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from Doan."
  },
  {
    id: 11,
    name: "Slieve Corragh",
    tagline: "Sliabh Corrach: Rugged/Pointed Mountain",
    image: "/images/slieve-corragh.jpg",
    height: "640m",
    lat: 54.1453,
    lng: -5.9644,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Darragh Mc Conville"
  },
  {
    id: 12,
    name: "Slievemartin",
    tagline: "Sliabh Mártain: Martins Mountain",
    image: "/images/slieve-martin.jpg",
    height: "485m",
    lat: 54.1053,
    lng: -6.0736,
    terrain: "Mostly gravel paths or tracks through the forest if approaching from Rostrevor/Kilbroney Park. Nearer the summit is mostly grass & heather.",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from the Warrenpoint/Rostrevor Road."
  },
  {
    id: 13,
    name: "Shanlieve",
    tagline: "Seanshliabh: Old Mountain",
    image: "/images/shanlievefinlieve.jpg",
    height: "626m",
    lat: 54.1142,
    lng: -6.0342,
    terrain: "Shanlieve sits like a giant on top of Tievedockaragh. It is quite a steep climb and the area between is extremely boggy.",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from the summit of Tievedockaragh."
  },
  {
    id: 14,
    name: "Finlieve",
    tagline: "Fionnshliabh: White Mountain",
    image: "/images/slieve-martin-background1.jpg",
    height: "583m",
    lat: 54.1094,
    lng: -6.0444,
    terrain: "Heather & lots of it.",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland."
  },
  {
    id: 15,
    name: "Eagle Mountain",
    tagline: "Sliabh an Iolair: Mountain of the eagle",
    image: "/images/eagle-mountain.jpg",
    height: "638m",
    lat: 54.1042,
    lng: -6.0150,
    terrain: "Rocky with well worn grass in places & therefore muddy. On approaching from the Windy Gap the grass/heather is quite wet.",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from the summit of Tievedockaragh."
  },
  {
    id: 16,
    name: "Pigeon Rock Mountain",
    tagline: "Droim Lao: Ridge of the calf",
    image: "/images/pigeon-rock-mountain.jpg",
    height: "534m",
    lat: 54.1072,
    lng: -5.9958,
    terrain: "Grass & heather. Quite muddy in winter.",
    additional: "Although this mountain is called Pigeon Rock Mountain the old name is Droim Lao which means Ridge of the Calf.",
    photo: "This photo was taken by Michéal Mc Parland from the shore of Spelga Dam."
  },
  {
    id: 17,
    name: "Ott Mountain",
    tagline: "Ucht: Mountain-breast",
    image: "/images/ott-mountain1.jpg",
    height: "524m",
    lat: 54.1869,
    lng: -6.0003,
    terrain: "Ott is easily accesible via the gravel path just off Slievenaman Road. Once you come off the path to approach the summit the terrain is mostly heather & very wet in winter.",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from the Deers Meadow."
  },
  {
    id: 18,
    name: "Slieve Loughshannagh",
    tagline: "Sliabh Loch Seannach: Mountain of the lake of foxes",
    image: "/images/slieve-loughshannagh.jpg",
    height: "619m",
    lat: 54.1997,
    lng: -5.9711,
    terrain: "Heather & grass that gets quite wet in winter.",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland during the 2009 Braveheart walk."
  },
  {
    id: 19,
    name: "Carn Mountain",
    tagline: "Sliabh an Chairn: Mountain of the Cairn",
    image: "/images/carn-mountain.jpg",
    height: "588m",
    lat: 54.1875,
    lng: -5.9447,
    terrain: "Heather & grass that gets quite wet in winter.",
    additional: "",
    photo: "This photo was taken by Michéal during the 2009 Braveheart hike."
  },
  {
    id: 20,
    name: "Tievedockaragh",
    tagline: "Taobh Docrach: Difficult side/slope",
    image: "/images/tievedockaragh.jpg",
    height: "473m",
    lat: 54.1069,
    lng: -6.0264,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from the side of Tievedockaragh."
  },
  {
    id: 21,
    name: "Altataggart Mountain",
    tagline: "Allt an tSagairt: Mountain/glen of the priest",
    image: "/images/altataggart-mountain.jpg",
    height: "420m",
    lat: 54.1558,
    lng: -6.0219,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from Sandbank Road."
  },
  {
    id: 22,
    name: "Hen Mountain",
    tagline: "Sliabh na Circe: Mountain of the hen",
    image: "/images/henfromshanlieve.jpg",
    height: "354m",
    lat: 54.1172,
    lng: -6.0572,
    terrain: "Gravel path then grass/heather.",
    additional: "",
    photo: "Taken from the slopes of Shanlieve. This photo was taken by Michéal Mc Parland."
  },
  {
    id: 23,
    name: "Cock Mountain",
    tagline: "Sliabh an Choiligh: Mountain of the Cock",
    image: "/images/cock-mountain.jpg",
    height: "505m",
    lat: 54.1236,
    lng: -6.0653,
    terrain: "Rough heather.",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland. Hen mountain is in the foreground."
  },
  {
    id: 24,
    name: "Slievenamiskan",
    tagline: "Sliabh Meáscain: measeáin shaped mountain",
    image: "/images/slievenamiskan.jpg",
    height: "444m",
    lat: 54.1183,
    lng: -5.9875,
    terrain: "Rough heather.",
    additional: "",
    photo: "This photo was taken by Michéal Mc Parland from the Deers Meadow at the foot of Pigeon Mountain."
  },
  {
    id: 25,
    name: "Butter Mountain",
    tagline: "Sliabh an Ime: Mountain of the butter",
    image: "/images/butter-mountain.jpg",
    height: "490m",
    lat: 54.1336,
    lng: -5.9964,
    terrain: "Rough heather.",
    additional: "This mountain derives its name from the custom of burying or storing butter there",
    photo: "This photo was taken by Michéal Mc Parland from the Deers Meadow."
  },
  {
    id: 26,
    name: "Slievemoughanmore",
    tagline: ".",
    image: "/images/slievemoughanmorerange.jpg",
    height: "559m",
    lat: 54.1478,
    lng: -6.0236,
    terrain: "Grass/heather.",
    additional: "",
    photo: "Taken by Michéal Mc Parland."
  },
  {
    id: 27,
    name: "Rocky Mountain",
    tagline: "Sliabh na gCloch: Mountain of the stones/rocks",
    image: "/images/rockymountain.jpg",
    height: "405m",
    lat: 54.1606,
    lng: -6.0133,
    terrain: "Grass/Heather",
    additional: "This is one of three mountains with the name Rocky.",
    photo: "This photo was taken by Jarlath Gray from the side of Altataggart."
  },
  {
    id: 28,
    name: "Slievemageogh",
    tagline: "Sliabh Mhig Eothach: Mageoghs mountain",
    image: "/images/slievemageogh.jpg",
    height: "316m",
    lat: 54.1733,
    lng: -6.0408,
    terrain: "Rough heather.",
    additional: "",
    photo: "This photo was taken by Conor Brady from Sandy Brae track."
  },
  {
    id: 29,
    name: "The Mourne Mountains",
    tagline: "Na Beanna Boirche",
    image: "/images/annalong-valley.jpg",
    height: "",
    lat: 54.16,
    lng: -5.97,
    terrain: "",
    additional: "",
    photo: "This photo was taken by Peter Barr from the Slieve Binnian."
  }
];
